# ไฟล์ .gitlab-ci.yml ใน thai-address repository
variables:
  ATP_FRONTEND_PROJECT_ID: "57"
  ATP_FRONTEND_BRANCH: "main"
  TRIGGER_TOKEN: "glptt-3143a18c773f8173bc95ee4cd00f06d28b43cf4d"

stages:
  - trigger

trigger-atp-frontend:
  stage: trigger
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # trigger เมื่อมีการ push เข้า main branch
  script:
    - |
      curl --request POST \
        --form "token=${TRIGGER_TOKEN}" \
        --form "ref=${ATP_FRONTEND_BRANCH}" \
        "https://gitlab.com/api/v4/projects/${ATP_FRONTEND_PROJECT_ID}/trigger/pipeline"