variables:
  ATP_FRONTEND_PROJECT_ID: "57"
  ATP_FRONTEND_RIGGER_TOKEN: "glptt-3143a18c773f8173bc95ee4cd00f06d28b43cf4d"

stages:
  - trigger

.trigger_template: &trigger_definition
  stage: trigger
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trigger-atp-frontend:
  <<: *trigger_definition
  script: |
    curl -X POST --fail \
      -F token=${TRIGGER_TOKEN} \
      -F ref=dev \
      https://gitlab.autopair.co/api/v4/projects/${ATP_FRONTEND_PROJECT_ID}/trigger/pipeline

    curl -X POST --fail \
      -F token=${TRIGGER_TOKEN} \
      -F ref=prod-demo \
      https://gitlab.autopair.co/api/v4/projects/${ATP_FRONTEND_PROJECT_ID}/trigger/pipeline

    curl -X POST --fail \
      -F token=${TRIGGER_TOKEN} \
      -F ref=prod \
      https://gitlab.autopair.co/api/v4/projects/${ATP_FRONTEND_PROJECT_ID}/trigger/pipelines